class Airplane:
    def __init__(self):
        self.color = ...
        self.speed = ...
        self.capacity = ...
        self.country = ...
        self.model = ...

    def turnon(self):
        ...
    
    def turnoff(self):
        ...

    def fly(self):
        ...
    
class Car:
    def __init__(self):
        self.speed = ...
        self.color = ...
        self.license_plate = ...
        self.model = ...
        self.capacity = ...
        self.number_of_wheels = ...

    def turn_on(self):
        ...
    
    def turn_off(self):
        ...

    def boogh(self):
        ...


class Bicycle:
    def __init__(self):
        self.color = ...
        self.model = ...
        self.speed = ...
        self.number_of_wheels = ...

    def 